<title>CADnaukri.com | Background Check</title>
<div class="container top-btm-space">
			<h1 class="orange">Background Check</h1>
			<div class="full">
				<p>CADnaukri.com or any of its associates do not verify any document provided by the candidates physically .
				 Candidates are instructed to provide the soft-copies of their credentials only when it becomes necessary 
				 in the registration process.
			</p>
			
			<p>The user consents to the display of those portions of his/her profile, which have been positively verified 
			as long as profile is otherwise searchable.</p>
           
           <p>In order to have the verification report removed from the profile, a user will have to approach CADnaukri.com 
           with written request in this regard.
           </p>
          
           <p>
           The verification report shall be prepared by another party - the service provider - based on information provided by 
           the user/subscriber and shall not be generated by CADnaukri.com in house; the reports are merely being delivered 
           through the channels of CADnaukri.com
           </p>     
         
          <p>
          A job-seeker, on purchase of background check as a service, has to fill up the verification form within 30 days of 
          buying of service, failing which the link to the form shall expire. The verification process will be closed if we
          are unable to verify the facts due to insufficient information; in such an event, there be no refund of money. 
          Any request for re-verification thereafter, will be treated as a fresh transaction and appropriate charges shall apply. 

          </p>
         
      
          <p>Timelines shall be counted only from the date & time of receipt of the documents. CADnaukri.com will not be liable
           for delay which may be caused due to late delivery/loss of documents sent to us by post/courier.</p>
        
          <p>The background check service is not carried on behalf of employers, who may choose to scrutinise further.</p>
         
           <p>Any action taken by the user (jobseeker or recruiter) on the basis of background check report or otherwise, 
           is the user's responsibility alone and CADnaukri.com will not be liable in any manner for the consequence of 
           such action taken by the user.</p>
        
           <p>The user of the services doesn't claim any copyright or other Intellectual Property Rights over the data uploaded 
           by him/her on the website.</p>
        
           <p>Jurisdiction for any dispute arising from and related to this shall be in the courts of Bhubaneswar (India)
            to the exclusion of all other courts.</p>
         
           <p>All disputes shall be resolved in accordance with the laws of India as applicable.</p>
      
          <p>The users are bound by the terms and the conditions as mentioned supra. Registration presumes that the user 
          have read, understood and accepted the terms and conditions. This service is live in India for the present.</p>
         <br />
      
        
          <br/>
        
		</div>



		</div>